name: peer_node_connection
description: A peer to peer node connection
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1

dependencies:
  typed_event_emitter: ^1.0.0
  typed_messages: ^1.1.0
